M48
; DRILL file {KiCad (5.99.0-10394-g2e15de97e0)} date Mon Apr 26 17:42:35 2021
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2021-04-26T17:42:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-10394-g2e15de97e0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X11438Y6604
T0
M30
